<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>101836eb-fd66-4c1f-80d8-6810d2974290</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;adplus-dvertising&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e5c238f2-2c7f-4e4e-87c1-f170482de80b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ad.plus/adplus-advertising.svg</value>
      <webElementGuid>657aac80-df12-4442-a8f4-712980f4c767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>adplus-dvertising</value>
      <webElementGuid>767b6598-d2de-412e-8b84-37dc7b0ce01c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ad.Plus Advertising</value>
      <webElementGuid>6d783943-26d1-4376-8bee-bde8f8a7448c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;close-fixedban&quot;)/img[1]</value>
      <webElementGuid>91b902e4-8be8-443d-9ac7-be0faf875830</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='close-fixedban']/img</value>
      <webElementGuid>f19c960b-dd7d-4cb5-b48a-378a46370c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='adplus-dvertising']</value>
      <webElementGuid>aa36e095-47d7-46ce-a840-d479df9a956f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>bb0239bf-0bdf-4d81-9321-68a81b43d7d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ad.plus/adplus-advertising.svg' and @alt = 'adplus-dvertising' and @title = 'Ad.Plus Advertising']</value>
      <webElementGuid>d1249bbb-b6e0-4771-9439-4aad05fa58ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
